language: node_js
node_js:
  - "node"
before_script: sudo redis-server /etc/redis/redis.conf --port 6379
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
